wedding_planner/config/routes.rb
Rails.application.routes.draw do

  root to: "welcome#index"
  resources :guests do
    resources :place_cards
  end
  resources :users
  resource  :session
end

wedding_planner/app/models/guest.rb
class Guest < ActiveRecord::Base
   # NHO: validations!
   validates :mailing_title, :last_name, presence: true
   has_many :place_cards, dependent: :destroy
   belongs_to :user

   # NHO: something to consider in the future might be to write some model methods to help with custom queries or
   # combining data to make a new property
   # i.e. an method that returns a guest's full name
   # or a method that finds all the guests that have not yet been sent an invite

end

wedding_planner/app/models/place_card.rb
class PlaceCard < ActiveRecord::Base
  belongs_to :guest
  belongs_to :user # NHO: I think this is unnecessary since a user has access to placecards through guests already
end

wedding_planner/app/models/user.rb
class User < ActiveRecord::Base
   has_many :guests
   validates :username, presence: true
 end

wedding_planner/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_current_user

    def get_current_user
      if User.exists?(session[:user_id])
        @current_user = User.find(session[:user_id])
      else
        @current_user = nil
      end
    end

end

wedding_planner/app/controllers/concerns/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  # new
def new
  @guest = Guest.new
end

  def create
    @guest = Guest.create!(guest_params)
    redirect_to @guest
  end

  # edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # update
  def update
    @guest = Guest.find(params[:id])
    @guest.update(guest_params)
    redirect_to guest_path(@guest)
  end

  # destroy
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to guests_path
  end

  private
  def guest_params
    params.require(:guest).permit(:mailing_title, :first_name, :last_name, :spouse_first_name, :spouse_last_name,
                   :address_line1, :address_line2, :city, :state, :zip, :country, :relationship, :email, :spouse_email,
                   :send_invitation, :gift_received, :thank_you_sent)
  end
end

wedding_planner/app/controllers/concerns/place_cards_controller.rb
class PlaceCardsController < ApplicationController

  # index
  def index
    @place_cards = PlaceCard.all
  end

  # new
  def new
    @guest = Guest.find(params[:guest_id])
    @place_card = @guest.place_cards.new
  end


  # create
  def create
    @guest = Guest.find(params[:guest_id])
    @placecard = @guest.place_cards.create!(place_card_params)
    redirect_to [@guest,@placecard]
  end

  #show
  def show
    @place_card = PlaceCard.find(params[:id])
  end

  # edit
  def edit
    @guest = Guest.find(params[:guest_id])
    @placecard = @guest.place_cards.find(params[:id])
  end

  # update
  def update
    @guest = Guest.find(params[:guest_id])
    @placecard = @guest.place_cards.find(params[:id])
    @placecard.update(place_card_params)
    redirect_to [@guest,@placecard]
  end

  # destroy
  def destroy
    @guest = Guest.find(params[:guest_id])
    @placecard = @guest.place_cards.find(params[:id])
    @placecard.destroy
    redirect_to @guest
  end

  private
  def place_card_params
    params.require(:place_card).permit(:name, :table_number, :print)
  end

end

wedding_planner/app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  # NHO: think you can DRY up this controller by making a before_action that will run a method
  # to redirect_to the root_path unless there is a current_user
  def index
    redirect_to root_path unless @current_user
    @guests = @current_user.guests
  end

  def show
    @guest = Guest.find(params[:id])
  end

  # new
def new
  redirect_to root_path unless @current_user
  @guest = @current_user.guests.new
end

  def create
    redirect_to root_path unless @current_user
    @guest = @current_user.guests.new(guest_params)
    if @guest.save
       redirect_to guests_path
    else
      render "new"
    end
  end

  # edit
  def edit
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:id])
  end

  # update
  def update
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:id])
    @guest.update(guest_params)
    redirect_to guests_path
  end

  # destroy
  def destroy
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to guests_path
  end

  private
  def guest_params
    params.require(:guest).permit(:mailing_title, :first_name, :last_name, :spouse_first_name, :spouse_last_name,
                   :address_line1, :address_line2, :city, :state, :zip, :country, :relationship, :email, :spouse_email,
                   :send_invitation, :gift_received, :thank_you_sent)
  end
end

wedding_planner/app/controllers/place_cards_controller.rb
class PlaceCardsController < ApplicationController
  # NHO: which line is duplicated throughout this controller?
  # How could you use a before action to find a guest?
  
  # index
  def index
    @guest = Guest.find(params[:guest_id])
    @place_cards = @guest.place_cards
  end

  # new
  def new
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:guest_id])
    @place_card = @guest.place_cards.new
  end


  # create
  def create
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:guest_id])
    @place_card = @guest.place_cards.create!(place_card_params)
    redirect_to [@guest,@place_card]
  end

  #show
  def show
    @guest = Guest.find(params[:guest_id])
    @place_card = PlaceCard.find(params[:id])
  end

  # edit
  def edit
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:guest_id])
    @place_card = @guest.place_cards.find(params[:id])
  end

  # update
  def update
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:guest_id])
    @place_card = @guest.place_cards.find(params[:id])
    @place_card.update(place_card_params)
    redirect_to [@guest,@place_card]
  end

  # destroy
  def destroy
    redirect_to root_path unless @current_user
    @guest = Guest.find(params[:guest_id])
    @place_card = @guest.place_cards.find(params[:id])
    @place_card.destroy
    redirect_to guests_path
  end

  private
  def place_card_params
    params.require(:place_card).permit(:name, :table_number, :print)
  end

end

wedding_planner/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # NHO: nice job rolling your own User Auth!
    def new
      @user = User.new
    end

    def create
      input_username = params[:user][:username]
      if User.exists?(username: input_username)
        @user = User.find_by(username: input_username)
        if @user.password === params[:user][:password]
          flash.now[:notice] = "You're signed in!"
          session[:user_id] = @user.id
          @guest =  @user.guests
          redirect_to guests_path(@guest)
        else
          puts "Wrong password!" # NHO: these won't display to the user, I think you want a flash notification here
          redirect_to new_session_path
        end
      else
        puts "That user doesn't exist!" # NHO: these won't display to the user, I think you want a flash notification here
        redirect_to new_session_path
      end
    end

    def destroy
      reset_session
      puts "You're signed out!" # NHO: these won't display to the user, I think you want a flash notification here
      redirect_to :root
    end

end

wedding_planner/app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index
   @users = User.all
 end

 def new
   @user = User.new
 end

 def show
   @user = User.find(params[:id])
 end

 def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to guests_path
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_path unless @current_user == @user # NHO: nice!
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_path unless @current_user == @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end


 private
 def user_params
   params.require(:user).permit(:username, :password)
 end

end

wedding_planner/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

wedding_planner/app/helpers/application_helper.rb
module ApplicationHelper
end

wedding_planner/app/views/guests/_form.html.erb
<%= form_for @guest do |f| %>
  <%= f.label :mailing_title %>
  <%= f.text_field :mailing_title %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :spouse_first_name %>
  <%= f.text_field :spouse_first_name %>
  <%= f.label :address_line1 %>
  <%= f.text_field :address_line1 %>
  <%= f.label :address_line2 %>
  <%= f.text_field :address_line2 %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.label :relationship %>
  <%= f.text_field :relationship %>
  <%= f.label :email %>
  <%= f.text_field :email%>
  <%= f.label :spouse_email %>
  <%= f.text_field :spouse_email%>
  <%= f.label :send_invitation %>
  <%= f.check_boxh :send_invitation %>
  <%= f.label :gift_received %>
  <%= f.text_field :gift_received%>
  <%= f.label :thank_you_sent%>
  <%= f.check_box :thank_you_sent %>

  <%= f.submit %>
<% end %>

wedding_planner/app/views/guests/bootstrap.new.html.erb
  <!-- NHO: is this file being used currently? If not I'd recommend leaving it on another branch to go back to...  -->
<div class="container">
  <form class="form-horizontal" id="form_members" role="form">
    <legend>Guests</legend>
    <div class="form-group">
      <label for="mailing_title" class="col-sm-2">Mailing Title</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name="mailing_title" id="name" placeholder="Mailing Title">
      </div>
      <label for="firstname" class="col-sm-2">First Name</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name="first_name" id="firstname" placeholder="First Name">
      </div>
      <label for="lastname" class="col-sm-2">Last Name</label>
      <div class="col-sm-4">
        <input type="text" class="form-control" name="last_name" id="lastname" placeholder="Last Name">
      </div>
    </div>
    <div class="form-group">
    </div>
    <label for="firstname" class="col-sm-2">Spouse First Name</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="spouse_first_name" id="firstname" placeholder="Spouse First Name">
    </div>
    <label for="lastname" class="col-sm-2">Spouse Last Name</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="spouse_last_name" id="lastname" placeholder="Spouse Last Name">
    </div>
  </div>
  <legend>Address</legend>
  <div class="form-group">
    <label for="address" class="col-sm-2">Address</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="address_line1" id="address" placeholder="Address Line 1">
    </div>
    <label for="address" class="col-sm-2">Address</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="address_line2" id="address" placeholder="Address Line 2">
    </div>
    <label for="city" class="col-sm-2">City</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="city" id="city" placeholder="City">
    </div>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="state" id="state" placeholder="State">
    </div>
  </div>
  <div class="form-group">
    <label for="zipcode" class="col-sm-2">ZIP Code</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" name="zip" id="zipcode" placeholder="ZIP Code">
    </div>
    <input type="region" class="form-control" name="country" id="region" placeholder="Country">
    <label for="country" class="col-sm-2">Country</label>
  </div>
  <div class="col-sm-4">
    <label class="radio-inline">
      <input type="radio" name="relationship" id="male" value="friend"> Friend
    </label>
    <label class="radio-inline">
      <input type="radio" name="relationship" id="male" value="family"> Family
    </label>
    <label class="radio-inline">
      <input type="radio" name="relationship" id="male" value="acquaintance"> Professional Aquaintance
    </label>
  </div>
  <legend>Contact Info</legend>
  <div class="form-group">
    <label for="email" class="col-sm-2">Email</label>
    <div class="col-sm-4">
      <input type="email" class="form-control" name="email" id="email" placeholder="Email">
    </div>
    <label for="email" class="col-sm-2">Email</label>
    <div class="col-sm-4">
      <input type="email" class="form-control" name="spouse_email" id="email" placeholder="Spouse's Email">
    </div>
    <div class="checkbox">
      <label><input type="checkbox" name="send_invitation"> Send Invitation</label>
    </div>
  </div>
  <label for="comments" class="col-sm-2" >Gift Recieved</label>
  <div class="col-sm-4">
    <input type="email" class="form-control" name="gift_received" id="address" placeholder="Gift Received">
  </div>
</div>
<div class="checkbox">
  <label><input type="checkbox" name=thank_you_sent> Thank you Card Sent? </label>
</div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-warning" name="submit" id="submit">Submit</button>
  </div>
</div>
</form>
</div>

wedding_planner/app/views/guests/edit.html.erb
<h2  class="text-center" id = "ultimate-orange">Edit Guest</h2>

<%= form_for @guest do |f| %>
  <%= f.label :mailing_title %>
  <%= f.text_field :mailing_title, :size => 50 %>
  <div class = "invisible">
    ,
  </div>
  <div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :spouse_first_name %>
  <%= f.text_field :spouse_first_name %>
  <%= f.label :spouse_last_name %>
  <%= f.text_field :spouse_last_name %>
</div>
<div class = "invisible">
.
</div>
<div>
  <%= f.label :address_line1 %>
  <%= f.text_field :address_line1 %>
  <%= f.label :address_line2 %>
  <%= f.text_field :address_line2 %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :country %>
  <%= f.text_field :country %>
</div>
<div class = "invisible">
  .
</div>
  <%= f.radio_button :relationship, "Bride Family" %>
  <%= f.label :relationship, "Bride Family" %>
  <%= f.radio_button :relationship, "Bride Friend" %>
  <%= f.label :relationship, "Bride Friend" %>
  <%= f.radio_button :relationship, "Groom Family" %>
  <%= f.label :relationship, "Groom Family" %>
  <%= f.radio_button :relationship, "Groom Friend" %>
  <%= f.label :relationship, "Groom Friend" %>
  <%= f.radio_button :relationship, "Friend" %>
  <%= f.label :relationship, "Friend" %>
  <div class = "invisible">
    .
  </div>
  <%= f.label :email %>
  <%= f.text_field :email%>
  <%= f.label :spouse_email %>
  <%= f.text_field :spouse_email%>
<div class = "invisible">
    ,
  </div>
  <%= f.label :send_invitation %>
  <%= f.check_box :send_invitation %>
  <%= f.label :gift_received %>
  <%= f.text_field :gift_received%>
  <%= f.label :thank_you_sent%>
  <%= f.check_box :thank_you_sent %>

  <h5 class="text-center" id = "ultimate-orange-smaller"><%= f.submit %></h5>
<% end %>

<h4 class="text-center" id = "ultimate-orange-smaller">
  <%= form_for @guest, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
  <% end %>
</h4>
<div class = "invisible">
.
</div>
<nav>
  <h4 class="text-center" id = "ultimate-orange-smaller"><%= link_to "Back to Home Page", guests_path%></h4>
</nav>

wedding_planner/app/views/guests/index.html.erb
<form class="form-horizontal" role="form">
  <div class = "container-fluid">
    <div class = "col-md-4"></div>
      <div class = "col-md-4">
         <h1 class="text-center" id = "ultimate-orange">Guest List</h1>
      </div>
        <div class = "col-md-4"></div>
 </div>

  <% @guests.each do |guest| %>
  <div class="row">
      <h4  id = "ultimate-orange-smaller"><div class="col-sm-1"></div><div class="col-sm-1"></div><div class="col-sm-1"></div><div class="col-sm-4"><%= link_to guest.mailing_title, edit_guest_path(guest)%></div><div class="col-sm-4"><%= link_to "Input Place Cards", guest_place_cards_path(guest)%></div></h4>
  </div>
  <% end %>
</form>
<nav>
   <h2 id = "ultimate-orange"><span class="pull-left"><%= link_to "Add Guest", new_guest_path %></span><span class="pull-right"><%= link_to "Sign Out", session_path, method: :delete %></span></h2>
</nav>

wedding_planner/app/views/guests/new.html.erb
<!-- NHO: looks like you have some duplicaate between the form for New and Edit -->
<!-- I think you can abstract this into a form partial  -->
<h2  class="text-center" id = "ultimate-orange">New Guest</h2>

<% if @guest.errors.any? %>
  <% @guest.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
  <strong>SORRY! </strong><%= message %></div>
  <% end %>
<% end %>

<%= form_for @guest do |f| %>
  <%= f.label :mailing_title %>
  <%= f.text_field :mailing_title, :size => 50 %>
  <div class = "invisible">
    ,
  </div>
  <div>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :spouse_first_name %>
  <%= f.text_field :spouse_first_name %>
  <%= f.label :spouse_last_name %>
  <%= f.text_field :spouse_last_name %>
</div>
<div class = "invisible">
.
</div>
<div>
  <%= f.label :address_line1 %>
  <%= f.text_field :address_line1 %>
  <%= f.label :address_line2 %>
  <%= f.text_field :address_line2 %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :country %>
  <%= f.text_field :country %>
</div>
<div class = "invisible">
  .
</div>
  <%= f.radio_button :relationship, "Bride Family" %>
  <%= f.label :relationship, "Bride Family" %>
  <%= f.radio_button :relationship, "Bride Friend" %>
  <%= f.label :relationship, "Bride Friend" %>
  <%= f.radio_button :relationship, "Groom Family" %>
  <%= f.label :relationship, "Groom Family" %>
  <%= f.radio_button :relationship, "Groom Friend" %>
  <%= f.label :relationship, "Groom Friend" %>
  <%= f.radio_button :relationship, "Friend" %>
  <%= f.label :relationship, "Friend" %>
  <div class = "invisible">
    .
  </div>
  <%= f.label :email %>
  <%= f.text_field :email%>
  <%= f.label :spouse_email %>
  <%= f.text_field :spouse_email%>
  <div class = "invisible">
    ,
  </div>
  <%= f.label :send_invitation %>
  <%= f.check_box :send_invitation %>
  <%= f.label :gift_received %>
  <%= f.text_field :gift_received%>
  <%= f.label :thank_you_sent%>
  <%= f.check_box :thank_you_sent %>

  <div class = "invisible">
    .
  </div>

  <h5 class="text-center" id = "ultimate-orange">
    <%= f.submit %>
  </h5>
<% end %>
<div class = "invisible">
.
</div>
<nav>
  <h5 class="text-center"id = "ultimate-orange"><%= link_to "Back to Home Page", guests_path%></h5>
</nav>

wedding_planner/app/views/guests/show.html.erb
<h2><%= @guest.mailing_title %> <%= link_to("(edit)", edit_guest_path(@guest)) if @current_user %></h2>
<nav>
   <h2 id = "ultimate-orange"><span class="pull-left"><%= link_to "Add Guest", new_guest_path %></span><span class="pull-right"><%= link_to "Sign Out", session_path, method: :delete %></span></h2>
</nav>
<% flash.each do |type, message| %>
  <p><%= type %>: <%= message %></p>
<% end %>

wedding_planner/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>WeddingPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Cinzel+Decorative:400,700,900' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <style type="text/css"> body { background: beige; !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
  </style>  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class = "container-fluid">
    <div class = "col-md-4"><span class="pull-left"><%= image_tag("heart-vine-right.png") %></span></div>
      <div class = "col-md-4">
         <h1 class="text-center" id="ultimate">The Ultimate Wedding Planner</h1>
      </div>
        <div class = "col-md-4"><span class="pull-right"><%= image_tag("heart-vine-left.png") %></span></div>
 </div>
 <!-- NHO: careful of your indentation  -->
  <p></p>
  <!-- Since this block will show a message anywhere in your app, you don't need more than one of these blocks -->
  <% flash.each do |type, message| %>
    <p><%= type %>: <%= message %></p>
  <% end %>

</div>

<%= yield %>

</body>
</html>

wedding_planner/app/views/place_cards/_form.html.erb
<%= form_for[@guest,@place_card] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :table %>
  <%= f.text_field :table_number %>

  <div class="checkbox">
    <label><input type="checkbox"> print? </label>
    <%= f.check_box :print %>
  </div>

  <%= f.submit %>

<% end %>

wedding_planner/app/views/place_cards/edit.html.erb
  <h1 class="text-center" id = "ultimate-orange">Edit Place Cards</h1>

<%= form_for([@guest,@place_card]) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :table %>
  <%= f.text_field :table_number %>

  <%= f.label :print %>
  <%= f.check_box :print %>


  <%= f.submit %>

<% end %>

<nav>
   <h2 id = "ultimate-orange"><span class="pull-left"><%= link_to "Delete!", [@guest,@place_card], method: :delete, class: "delete" %></span><span class="pull-right"><%= link_to "Home Page", guests_path%></span></h2>
</nav>

wedding_planner/app/views/place_cards/index.html.erb
<!-- NHO: careful of your indentation here  -->
<h1 class="text-center" id = "ultimate">Place Cards</h1>
<h3 class="text-center"><% if @guest.place_cards.length >  0 %>
  <% @guest.place_cards.each do |place_card| %>
  <form class="form-horizontal" role="form">
    <div class = "row">
      <div class = "container-fluid">
        <div class = "col-md-1"></div>
        <div class = "col-md-1"></div>
        <div class = "col-md-1"></div>
        <h4 class = "col-md-6" id = "ultimate-orange-smaller"><span class="pull-left"> <%= link_to "#{place_card.name}", edit_guest_place_card_path(@guest,place_card) %></span> <span class="pull-right"> table number - <%= "#{place_card.table_number}"%></span></h4>
      </div>
    </div>
  </div>
  <% end %>
  <% end %> <!-- NHO: what does this <% end %> close? -->
</h3>

<div>
  <h2 class="text-center" id="ultimate-orange">
    <%= link_to "Add New Place Cards", new_guest_place_card_path(@guest) %>
  </h2>
</div>
<nav>
  <h4 id="ultimate-orange"><span class="pull-left"><%= link_to "Back to Home Page", guests_path%></span></h4>
</nav>

wedding_planner/app/views/place_cards/new.html.erb
<h1 class = "ultimate-orange">New Place Cards </h1>

<%= form_for([@guest,@place_card]) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :table %>
  <%= f.text_field :table_number %>

  <%= f.label :print %>
  <%= f.check_box :print %>

  <%= f.submit %>

<% end %>
<nav>
   <h2 id = "ultimate-orange"><%= link_to "Home Page", guests_path%></h2>
</nav>

wedding_planner/app/views/place_cards/show.html.erb
<h3  class="text-center" id = "ultimate-orange"><%= @guest.mailing_title %>'s Place Cards</h3>

 <% if @guest.place_cards.length >  0 %>
     <% @guest.place_cards.each do |place_card| %>
    <ul>
       <h3  class="text-center" id = "ultimate-orange-smaller"><%= link_to "#{place_card.name} - table number -  #{place_card.table_number}", edit_guest_place_card_path(@guest,place_card) %></h3>
   </ul>
   <% end %>
<% end %>
<h3  class="text-center" id = "ultimate-orange"><%= link_to "Add A New Place Card", new_guest_place_card_path(@guest) %></h3>
</h3>
<nav>
  <h3 id = "ultimate-orange"><%= link_to "Back to Home Page", guests_path%></hs>
</nav>

wedding_planner/app/views/users/application.html.erb
<!-- NHO: can you move these link to the actual application.html.erb and delete this file?  -->
<%= link_to "Sign Up", new_user_path %>
<%= link_to "Users Sign In", user_path %>

wedding_planner/app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>
 <%= form_for @user do |f| %>
   <%= f.label :username %>
   <%= f.text_field :username %>

   <%= f.label :password %>
   <%= f.password_field :password %>

   <%= f.submit "Submit" %>
 <% end %>
 <nav>
   <h4><%= link_to "Back to Home Page", guests_path%></h4>
 </nav>

wedding_planner/app/views/users/index.html.erb
<!-- NHO: Is this a feature you want to support, displaying all users?  -->
<h2>Users</h2>
 <ul>
   <% @users.each do |user| %>
     <li><%= link_to user.username, user %></li>
   <% end %>
 </ul>
 <nav>
   <h4><%= link_to "Back to Home Page", guests_path%></h4>
 </nav>

wedding_planner/app/views/users/new.html.erb
<h2 id = "ultimate-orange">Sign Up</h2>
<%= form_for @user do |f| %>
 <%= f.label :username %>
 <%= f.text_field :username %>

 <%= f.label :password %>
 <%= f.password_field :password %>

 <%= f.submit "Submit" %>
<% end %>
<nav>
  <h2><span id="ultimate-orange" class="pull-left"><%= link_to "Back to Home Page", root_path%></span></h2>
</nav>

wedding_planner/app/views/users/show.html.erb
<h2><%= @user.username %> <%= link_to("(edit)", edit_user_path(@user)) if @current_user == @user %></h2>

wedding_planner/app/views/welcome/index.html.erb
<nav>
  <% if @current_user %>
       <h2 id = "ultimate-orange"><span class="pull-left"><%= link_to "Welcome, #{@current_user.username}!", user_path(@current_user) %></span><span class="pull-right"><%= link_to "Sign Out", session_path, method: :delete %></span></h2>
    <% else %>
      <h2 id = "ultimate-orange"><span class="pull-left"><%= link_to "Sign Up", new_user_path %></span><span class="pull-right"><%= link_to "Sign In", new_session_path %></span></h2>
    <% end %>
</nav>
<% flash.each do |type, message| %>
  <p><%= type %>: <%= message %></p>
<% end %>